version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=payment
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data
networks:
  net:
    driver: bridge
    name: net

volumes:
  db:
    driver: local
# This Docker Compose file runs the db seruce, which can be use for actual API calls testing, and also the integration tests.
# Make sure to have Docker Installed and Running before composing or testing
